# Generated by Django 5.2.1 on 2025-10-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('pharmacie', '0002_alter_depense_options_alter_depense_categorie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Réquisition', 'verbose_name_plural': 'Réquisitions'},
        ),
        migrations.AddField(
            model_name='requisition',
            name='auto_genere',
            field=models.BooleanField(default=False, help_text='Créée automatiquement par le système'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='comptes.pharmacie'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='produit_fabricant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='pharmacie.produitfabricant'),
        ),
    ]
