# Generated by Django 5.2.1 on 2025-10-22 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('pharmacie', '0003_alter_requisition_options_requisition_auto_genere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMensuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.PositiveIntegerField()),
                ('mois', models.PositiveSmallIntegerField()),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_depenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_benefice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('croissance_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('croissance_benefice', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_mensuels', to='comptes.pharmacie')),
            ],
            options={
                'verbose_name': 'Rapport mensuel',
                'verbose_name_plural': 'Rapports mensuels',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('pharmacie', 'annee', 'mois')},
            },
        ),
    ]
