# Generated by Django 5.2.1 on 2025-12-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_rapportmensuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportmensuel',
            name='croissance_benefice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rapportmensuel',
            name='croissance_ventes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
